Task3
ipelekhan/video-course pull request #3
Opened 2020-10-28 03:31 UTC by ipelekhan

- [ ] Finish previous task (add `@Output` and simple routing)
- [ ] Make use of `ngModule`
- [ ] Add service with Observable
- [ ] Add `@testing-library/angular` and write a test with it
- [ ] Increase coverage
- [ ] Fix broken unit tests
- [ ] Add more tests!

2020-10-29 06:39 UTC, dragonflypl commented on src/app/app.component.spec.ts
> +      imports: [RouterTestingModule, LayoutModule, CoursesModule],
Nice job

2020-10-29 06:41 UTC, dragonflypl commented on src/app/courses/course-item/course-item.component.spec.ts
> +        deleteCourseRequest: {
you don't need to pass it

2020-10-29 06:47 UTC, dragonflypl requested changes
Good job.

Next time:
- please do changes not related to homework in separate commits (like modules refactoring). It is hard to check howework when there is this amoun of changes
- I didn't see `Test host testing` case. Please add it (e.g. create test for pipes with test host component.

2020-10-29 07:01 UTC, ipelekhan commented
Hm, not sure what to fix. On my both machine it's green:
![image](https://user-images.githubusercontent.com/2616427/97536129-fd59d100-19bc-11eb-9458-db02d9aebf64.png)

2020-10-29 07:03 UTC, ipelekhan commented on src/app/courses/course-item/course-item.component.spec.ts
> +        deleteCourseRequest: {
Could you please elaborate?

2020-11-06 16:12 UTC, ipelekhan commented
@dragonflypl I am going to merge this PR, could you please mark `Task 3` as resolved at learn.epam.com?

2020-11-06 16:13 UTC, merged